import type {
  CollectionSchema,
  SchemaField,
  SchemaModel,
  SchemaProject,
  TypegenOptions,
} from "./types";

function isIdentifier(value: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value);
}

function fieldStorageName(field: SchemaField): string {
  if (field.mapped_name) return field.mapped_name;
  if (field.is_id) return "_id";
  return field.name;
}

function renderPropertyName(name: string): string {
  return isIdentifier(name) ? name : JSON.stringify(name);
}

function relationTarget(field: SchemaField, byModelName: Map<string, SchemaModel>): string {
  const target = field.relation?.model ? byModelName.get(field.relation.model) : undefined;
  if (!target) return "Record<string, JsonValue>";
  return target.name;
}

function scalarType(field: SchemaField, byModelName: Map<string, SchemaModel>): string {
  if (field.prisma_type === "Json") {
    return "JsonValue";
  }
  switch (field.type) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "datetime":
      return "string";
    case "array":
      return "JsonValue[]";
    case "object":
      return "Record<string, JsonValue>";
    case "relation":
      return relationTarget(field, byModelName);
    default:
      return "JsonValue";
  }
}

function fieldType(field: SchemaField, byModelName: Map<string, SchemaModel>): string {
  const base = scalarType(field, byModelName);
  if (field.type === "relation") {
    if (field.list) return `${base}[]`;
    return field.required ? base : `${base} | null`;
  }
  if (field.list && !base.endsWith("[]")) {
    return `${base}[]`;
  }
  return base;
}

function renderModel(model: SchemaModel, byModelName: Map<string, SchemaModel>): string {
  const lines: string[] = [];
  lines.push(`export interface ${model.name} {`);
  lines.push(`  _id: string;`);

  const fields = model.schema.fields ?? [];
  for (const field of fields) {
    if (fieldStorageName(field) === "_id") {
      continue;
    }
    const optional = field.required ? "" : "?";
    lines.push(`  ${renderPropertyName(field.name)}${optional}: ${fieldType(field, byModelName)};`);
  }

  lines.push(`}`);
  lines.push(`export type ${model.name}CreateInput = Omit<${model.name}, "_id">;`);
  lines.push(`export type ${model.name}UpdateInput = Partial<${model.name}CreateInput>;`);
  return lines.join("\n");
}

function renderDatabaseMap(project: SchemaProject): string {
  const lines: string[] = [];
  lines.push(`export interface VoidDbGeneratedCollections {`);
  for (const model of project.models ?? []) {
    const database = model.schema.database ?? "default";
    const collection = model.schema.collection ?? model.name;
    lines.push(`  ${JSON.stringify(`${database}/${collection}`)}: ${model.name};`);
  }
  lines.push(`}`);
  lines.push(``);
  lines.push(`export interface VoidDbGeneratedDatabases {`);

  const grouped = new Map<string, Array<{ collection: string; model: string }>>();
  for (const model of project.models ?? []) {
    const database = model.schema.database ?? "default";
    const collection = model.schema.collection ?? model.name;
    const bucket = grouped.get(database) ?? [];
    bucket.push({ collection, model: model.name });
    grouped.set(database, bucket);
  }

  for (const [database, collections] of grouped) {
    lines.push(`  ${JSON.stringify(database)}: {`);
    for (const entry of collections) {
      lines.push(`    ${JSON.stringify(entry.collection)}: ${entry.model};`);
    }
    lines.push(`  };`);
  }
  lines.push(`}`);
  return lines.join("\n");
}

export function generateTypeDefinitions(
  project: SchemaProject,
  options: TypegenOptions = {}
): string {
  const header = [
    `/* eslint-disable */`,
    `// Generated by @voiddb/orm${options.moduleName ? ` for ${options.moduleName}` : ""}.`,
    `// Do not edit by hand.`,
    ``,
    `export type JsonValue =`,
    `  | null`,
    `  | string`,
    `  | number`,
    `  | boolean`,
    `  | JsonValue[]`,
    `  | { [key: string]: JsonValue };`,
    ``,
  ];

  const byModelName = new Map<string, SchemaModel>();
  for (const model of project.models ?? []) {
    byModelName.set(model.name, model);
  }

  const body: string[] = [];
  for (const model of project.models ?? []) {
    body.push(renderModel(model, byModelName));
    body.push("");
  }
  body.push(renderDatabaseMap(project));
  body.push("");
  body.push(`export type VoidDbModelName = ${project.models.length > 0 ? project.models.map((model) => JSON.stringify(model.name)).join(" | ") : "never"};`);

  return [...header, ...body].join("\n");
}

export function modelSchemaLookup(project: SchemaProject): Map<string, CollectionSchema> {
  const out = new Map<string, CollectionSchema>();
  for (const model of project.models ?? []) {
    out.set(model.name, model.schema);
  }
  return out;
}
